spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

app:
  tables:
    ohcl: ${OHCL_TABLE}
    market-cap: ${MARKET_CAP_TABLE}
    merged: ${MERGED_TABLE}
    temp-merged: ${TEMP_TABLE}
    log: ${LOG_TABLE}